---
workflow:
  rules:
    # Runs on branches and merge requests but prevent duplicate pipelines (i.e., running on a branch associated with a merge request)
    # Reference: https://docs.gitlab.com/ee/ci/yaml/index.html#switch-between-branch-pipelines-and-merge-request-pipelines
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

variables:
  NODE_VERSION: 16

.npm:
  image: node:${NODE_VERSION}
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

lint:
  extends: .npm
  stage: test
  script:
    - npm run lint

test:
  extends: .npm
  stage: test
  script:
    - npm run ci:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    reports:
      cobertura: coverage/cobertura-coverage.xml
      junit: tests-xunit.xml
  parallel:
    matrix:
      - NODE_VERSION:
          - 16
